name: gobi
channels:
  - conda-forge
  - defaults
dependencies:
  # CORE / BASIC
  - python=3.10
  - pip
  - setuptools
  - wheel
  - ca-certificates

  # EXTENSION
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - h5py
  - gdal
  - statsmodels
  - tqdm

  # DEPENDENCIES
  - tk
  - readline
  - openssl
  - ncurses
  - libzlib
  - libsqlite
  - liblzma
  - libffi
  - libexpat
  - bzip2
