#
# GMT 6.3.0 Defaults file
#
# FONT Parameters
#
FONT_ANNOT_PRIMARY             = 12p,Helvetica,black
FONT_LABEL                     = 12p,Helvetica,black
FONT_TITLE                     = 16p,Helvetica,black
#
# FORMAT Parameters
#
FORMAT_GEO_MAP                 = D
#
# MAP Parameters
#
MAP_ANNOT_OFFSET_PRIMARY       = auto
MAP_ANNOT_OFFSET_SECONDARY     = auto
MAP_FRAME_TYPE                 = plain
MAP_LABEL_OFFSET               = auto
MAP_TICK_LENGTH_PRIMARY        = 2p/1p
MAP_TITLE_OFFSET               = 2p
#
# PostScript Parameters
#
PS_MEDIA                       = a4
